### ISSUE TITLE
Architecture Concerns

### ISSUE THREAD

**Issue by TerrenceHoStockpile** [TerrenceHo/autofresh#1]
### Watchman
Watchman requires it's own package. On initialization, query the watchman daemon using `watchman get-sockname` retrieving both the version and the socket name to connect to. Create a Unix Socket to watchman, and then on a separate goroutine, which takes in a channel called startChannel.
1. Watch Project: Send the directory to watch project
2. Subscribe: Subscribe to directory changes.  When changes are detected, send a message to startChannel.

### Build Phase
When a subscription detects a file change, then it sends a message to startChannel. A different goroutine receives this message from startChannel and triggers a build.  Before we trigger a build we clear the terminal screen. It is critical that we wait for the build to finish correctly. If the build does not result in errors, then we proceed to the running step.

If the build failed, then log all errors to console and do not proceed to running phase.  We have not killed the previous running process, so we can simply go back to waiting for a subscription notification to send to startChannel again.

### Running Phase
If a previous binary was already running, then we must kill the current running process using the PID. This will be accomplished using a channel, called stopChannel.  Once the previous process is killed, we can run our newly built binary, executing the process and spawning a new goroutine that takes a stopChannel, and waits to kill that process.

After we have successfully started the running process, then we go back to waiting for subscription changes.

### Cleanup
When autofresh is stopped, we must be sure to remove all running processes that were spawned, (so that we will not take up a port) Preferably, we can stop all goroutines before the main goroutine stops, so that we can exit(0).

**Comment by TerrenceHo** [comment]
Architecture has been implemented
/close
